org:
    sp:
        branches:
        - Hyderabad
        - Delhi
        - BAM
        - CH
        owner:
        - Ram Dayal
        - Ramkrushan Dayal
        - Mashes Dayal
        - Shyam Dayal
        phone:
        - 9090017305
        - 9938377478
        - 9338283990
        - 9190938490