
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: rootsole for browser access
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: system
    profiles:
        active: application3



